<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-V7AFDP1" failures="1" tests="3" name="Default test" time="73.039" errors="0" timestamp="2021-12-29T15:30:54 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="31.599"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="26.129"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="14.575">
    <failure type="java.lang.AssertionError" message="expected [My account - My Store] but found [508 Resource Limit Is Reached]">
      <![CDATA[java.lang.AssertionError: expected [My account - My Store] but found [508 Resource Limit Is Reached]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at cucumberPackage.loginTest.check_for_the_successful_login(loginTest.java:51)
at âœ½.check for the successful login(file:///C:/Users/Veeru%20%20Sai/Desktop/AutomationProject/src/test/resources/Features/loginAuth.feature:20)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
